spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: schema.sql
    data: data.sql
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8081