student:
  testing:
    system:
      answer.limit: 1
      resource.file:
        path: question-source_ru_RU.csv
        delimiter: ','
      localization:
        locale: ru

spring:
  messages:
    basename: i18n/bundle
    encoding: UTF-8

